### ISSUE TITLE
feature: disable recursive-ness in getInstalled Packages

### ISSUE THREAD

**Issue by BerkeleyTrue** [s-a/package.js#1]
Hey @s-a,

First off, great project! Code is super easy to grok. Looking to use it with one of my projects.

This is a feature request. By default it recurses through the packages directory to find all possible plugins. It would be great to be able to disable this. Thoughts?

**Comment by s-a** [comment]
This make sense. In past it should support nested dependencies by default but I understand that this could be time critcal. I d like to add an integer to ```autoload``` method parm which will describe how deep it should scan for packages.

**Comment by BerkeleyTrue** [comment]
awesome!
