### ISSUE TITLE
feature: using semvar or user provided function for expectedPackageIdentifier

### ISSUE THREAD

**Issue by BerkeleyTrue** [s-a/package.js#2]
Use case:

if my package updates and changes the interface it provides to plugins package.js has no way of throwing or notifying users that they are using outdated plugins that will conflict.

It is possible to use the interface itself to do version checking but it would be neat if either package.js used semvar instead of matching strings or was able to take in a function to run during checking.

**Comment by s-a** [comment]
I think a user defined function as ```expectedPackageIdentifier``` is a great idea. 
Let me drink a cup of tea and think about this :)


Guess you saw this already, but may be interesting for others...  
So far there exist ```loadedPlugins``` which I am using in this [test](https://github.com/s-a/package.js/blob/3d46d51cacb5293ed04c379e147f505ca50621a6/test/main.js#L63). Each plugin contains a ```meta``` object which holds the package.json content including version.  

Well to create an out of date alarm you have to know which version is the newest one. I am still impressed about the solution by wbond at https://github.com/wbond/package_control_channel. Maybe this is an inspiration for you too.

Feel free to keep me up to date with your ideas!

**Comment by s-a** [comment]
@BerkeleyTrue I have created a a new branch at  https://github.com/s-a/package.js/tree/identify. Maybe you want to check this out before I will merge this to master and publish to NPM registry.  

Since I ' ve marked ```expectedPackageIdentifier ``` as obsolete and introduced ```identify``` method this will be a breaking change. I think the new solution is much more elegant.

**Comment by BerkeleyTrue** [comment]
Sweet. Will take a look later today.

**Comment by s-a** [comment]
Just increased semantic MAJOR version to ```1.0.0``` because of incompatible API changes. Take a look at the [main tests](https://github.com/s-a/package.js/blob/7d1c46013bde3fcb6563bf8e8b649d776e1298fb/test/main.js#L73) to explore the new behavior.
